# Generated by Django 4.0.1 on 2022-01-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
