# Generated by Django 4.0.1 on 2022-01-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
